/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import beans.Agriculteur;
import beans.ProduitAgro;
import beans.VenteAgro;
import java.sql.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import services.AgriculteurService;
import services.ProduitService;
import services.VenteService;
import com.toedter.calendar.JDateChooser;
import static sun.net.www.MimeTable.loadTable; 

/**
 *
 * @author ayman
 */
public class VenteForm extends javax.swing.JInternalFrame {
    DefaultTableModel model;
    VenteService vs = new VenteService();

   public VenteForm() {
        initComponents();
        this.setClosable(true);
        this.setIconifiable(true);
        this.setMaximizable(true);
        this.setResizable(true);

        model = (DefaultTableModel) jTable1.getModel();
        model.setColumnIdentifiers(new String[]{"ID", "Agriculteur", "Produit", "Date", "Quantité"});
        
        loadCombos(); 
        loadTable(); 
    }
 private void loadCombos() {
        AgriculteurService as = new AgriculteurService();
        jComboBox1.removeAllItems();
        for (Agriculteur a : as.findAll()) {
            jComboBox1.addItem(a.getNom());
        }

        ProduitService ps = new ProduitService();
        jComboBox2.removeAllItems();
        for (ProduitAgro p : ps.findAll()) {
            jComboBox2.addItem(p.getNom());
        }
    }
 private void loadTable() {
        model.setRowCount(0);
        for (VenteAgro v : vs.findAll()) {
            model.addRow(new Object[]{
                v.getId(),
                v.getAgriculteur(),
                v.getProduit(),
                v.getDate(),
                v.getQuantite()
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        btnAjouter = new javax.swing.JButton();
        btnModifier = new javax.swing.JButton();
        btnSupprimer = new javax.swing.JButton();
        btnSuivre = new javax.swing.JButton();
        btnRevenus = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 255, 204));
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Gestion des ventes , Quanitité et Revenues");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 153));
        jLabel1.setText("Gestion de Ventes, Quanitité et Revenues:");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel2.setText("Agriculteur :");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel3.setText("Produit :");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel4.setText("Quantite : ");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel5.setText("Date :");

        jComboBox1.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jComboBox2.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnAjouter.setBackground(new java.awt.Color(102, 102, 255));
        btnAjouter.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        btnAjouter.setForeground(new java.awt.Color(255, 255, 255));
        btnAjouter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add.png"))); // NOI18N
        btnAjouter.setText("Ajouter");
        btnAjouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAjouterActionPerformed(evt);
            }
        });

        btnModifier.setBackground(new java.awt.Color(0, 153, 255));
        btnModifier.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        btnModifier.setForeground(new java.awt.Color(255, 255, 255));
        btnModifier.setIcon(new javax.swing.ImageIcon("C:\\Users\\USER\\Desktop\\refresh.png")); // NOI18N
        btnModifier.setText("Modifier");
        btnModifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModifierActionPerformed(evt);
            }
        });

        btnSupprimer.setBackground(new java.awt.Color(255, 153, 153));
        btnSupprimer.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        btnSupprimer.setForeground(new java.awt.Color(255, 255, 255));
        btnSupprimer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/delete.png"))); // NOI18N
        btnSupprimer.setText("Supprimer");
        btnSupprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSupprimerActionPerformed(evt);
            }
        });

        btnSuivre.setBackground(new java.awt.Color(204, 255, 204));
        btnSuivre.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        btnSuivre.setText("Suivre quantités");
        btnSuivre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuivreActionPerformed(evt);
            }
        });

        btnRevenus.setBackground(new java.awt.Color(153, 255, 153));
        btnRevenus.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        btnRevenus.setText("Estimer Revenues");
        btnRevenus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRevenusActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "Agriculteur", "Produit", "Date", "Quantité"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/img-revenue-removebg-preview.png"))); // NOI18N

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/img-revenue-removebg-preview.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jLabel7)
                        .addGap(83, 83, 83)
                        .addComponent(jLabel1)
                        .addGap(95, 95, 95)
                        .addComponent(jLabel6))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1026, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 804, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(298, 298, 298)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel3))
                                .addGap(59, 59, 59)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(44, 44, 44)
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(160, 160, 160)
                        .addComponent(btnAjouter)
                        .addGap(45, 45, 45)
                        .addComponent(btnModifier)
                        .addGap(57, 57, 57)
                        .addComponent(btnSupprimer)
                        .addGap(56, 56, 56)
                        .addComponent(btnSuivre)
                        .addGap(55, 55, 55)
                        .addComponent(btnRevenus)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(30, 30, 30)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(45, 45, 45)
                                        .addComponent(jLabel3))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(55, 55, 55)
                                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(31, 31, 31)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addComponent(jLabel7))
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAjouter)
                    .addComponent(btnModifier)
                    .addComponent(btnSupprimer)
                    .addComponent(btnSuivre)
                    .addComponent(btnRevenus))
                .addGap(100, 100, 100)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(130, 130, 130))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAjouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAjouterActionPerformed
 try {
        String nomAgri = jComboBox1.getSelectedItem().toString();
        String nomProd = jComboBox2.getSelectedItem().toString();
        
        int idAgri = 0;
        for (Agriculteur a : new AgriculteurService().findAll()) {
            if (a.getNom().equals(nomAgri)) { idAgri = a.getId(); break; }
        }
        
        int idProd = 0;
        for (ProduitAgro p : new ProduitService().findAll()) {
            if (p.getNom().equals(nomProd)) { idProd = p.getId(); break; }
        }

        double qte = Double.parseDouble(jTextField1.getText().trim());
        java.sql.Date sqlDate = new java.sql.Date(jDateChooser1.getDate().getTime());

        VenteAgro v = new VenteAgro(0, String.valueOf(idProd), String.valueOf(idAgri), sqlDate, qte);
        
        if (vs.create(v)) {
            JOptionPane.showMessageDialog(this, "Ajout effectué avec succès.");
            loadTable();
        }
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Erreur: Veuillez vous assurer de saisir un nombre dans le champ quantité.");
    }
    }//GEN-LAST:event_btnAjouterActionPerformed

    private void btnSupprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSupprimerActionPerformed
  int row = jTable1.getSelectedRow();
    if (row != -1) {
        int id = Integer.parseInt(jTable1.getValueAt(row, 0).toString());
        if (JOptionPane.showConfirmDialog(this, "Confirmation de la suppression.؟") == JOptionPane.YES_OPTION) {
            if (vs.delete(new VenteAgro(id, "", "", null, 0))) {
                loadTable();
                JOptionPane.showMessageDialog(this, "La suppression a été effectuée avec succès.");
            }
        }
    }
    }//GEN-LAST:event_btnSupprimerActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
       int row = jTable1.getSelectedRow();
        jComboBox1.setSelectedItem(model.getValueAt(row, 1).toString());
        jComboBox2.setSelectedItem(model.getValueAt(row, 2).toString());
        jDateChooser1.setDate((Date) model.getValueAt(row, 3));
        jTextField1.setText(model.getValueAt(row, 4).toString());
    }//GEN-LAST:event_jTable1MouseClicked

    private void btnModifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModifierActionPerformed
  int row = jTable1.getSelectedRow();
    if (row != -1) {
        try {
            int idVente = Integer.parseInt(jTable1.getValueAt(row, 0).toString());
            
            String nomAgri = jComboBox1.getSelectedItem().toString();
            String nomProd = jComboBox2.getSelectedItem().toString();
            
            int idAgri = 0;
            for (Agriculteur a : new AgriculteurService().findAll()) {
                if (a.getNom().equals(nomAgri)) { idAgri = a.getId(); break; }
            }
            
            int idProd = 0;
            for (ProduitAgro p : new ProduitService().findAll()) {
                if (p.getNom().equals(nomProd)) { idProd = p.getId(); break; }
            }

            double qte = Double.parseDouble(jTextField1.getText().trim());
            java.sql.Date sqlDate = new java.sql.Date(jDateChooser1.getDate().getTime());

            VenteAgro v = new VenteAgro(idVente, String.valueOf(idProd), String.valueOf(idAgri), sqlDate, qte);
            
            if (vs.update(v)) {
                JOptionPane.showMessageDialog(this, "La modification a été effectuée avec succès.");
                loadTable();
            } else {
                JOptionPane.showMessageDialog(this, "Échec de la modification dans la base de données.");
            }
            
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Erreur: Veuillez vérifier que les valeurs saisies sont des nombres valides.");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erreur: " + e.getMessage());
        }
    } else {
        JOptionPane.showMessageDialog(this, "Veuillez sélectionner une ligne du tableau afin de la modifier.");
    }
    }//GEN-LAST:event_btnModifierActionPerformed

    private void btnSuivreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuivreActionPerformed

        java.util.Map<String, Double> stats = vs.getQuantitesParProduit();
    
    StringBuilder sb = new StringBuilder(" Total des quantités vendues par produit.:\n\n");
    for (String prod : stats.keySet()) {
        sb.append("🔹 ").append(prod).append(" : ")
          .append(stats.get(prod)).append(" kg\n");
    }
    
    if(stats.isEmpty()) sb.append("Aucune vente pour le moment.ً.");
    
    javax.swing.JOptionPane.showMessageDialog(this, sb.toString(), "Suivi des Quantités", javax.swing.JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnSuivreActionPerformed

    private void btnRevenusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRevenusActionPerformed
    double total = vs.estimerRevenus();
    
    String message = " Revenus totaux estimés:\n\n" +
                     "Montant total: " + String.format("%.2f", total) + " DH";
    
    javax.swing.JOptionPane.showMessageDialog(this, message, "Estimation des Revenus", javax.swing.JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnRevenusActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VenteForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VenteForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VenteForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VenteForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VenteForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAjouter;
    private javax.swing.JButton btnModifier;
    private javax.swing.JButton btnRevenus;
    private javax.swing.JButton btnSuivre;
    private javax.swing.JButton btnSupprimer;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables

   
}
